### Tensors in Pytorch

1. 3 properties: dtype, device and layout.
2. Layout: default is strided which 

Usually arrays are stored in contiguous memory blocks of n-bit integers (or n/8 bytes).

https://www.youtube.com/watch?v=VlkzN00P0Bc

Strides can be changed in numpy as if the layout of the shape of array is different.



In [1]:
import torch
import numpy as np

ModuleNotFoundError: No module named 'torch'

In [ ]:
torch.__version__

'1.10.2+cu113'

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.version.cuda

'11.3'

In [ ]:
t = torch.Tensor()

In [ ]:
type(t)

torch.Tensor

In [ ]:
# Tensor attributes fundamental to pytorch

print(t.dtype) # different types for cpu and gpu
print(t.device)
print(t.layout) #default is strided # https://en.wikipedia.org/wiki/Stride_of_an_array

torch.float32
cpu
torch.strided


In [ ]:
device = torch.device("cuda:0")
device

device(type='cuda', index=0)

In [ ]:
# Every tensor concerning an operation should live on same device to do an operation on them

In [ ]:
data = np.array([1,2,3])
data.dtype, type(data)

(dtype('int64'), numpy.ndarray)

In [ ]:
# creates a copy of the array
# create a tensor with global default datatype float32
torch.Tensor(data) # initialized Tensor from class (constructor) and converts the data type to float

tensor([1., 2., 3.])

In [ ]:
# infers the datatype
# creates a copy of the array
torch.tensor(data) # factory function (creating objects without constructor of a class), does not change data type

tensor([1, 2, 3])

In [ ]:
# changes in place, shared memory, creates a view 
torch.as_tensor(data) # factory function

tensor([1, 2, 3])

In [ ]:
# changes in place, shared memory, creates a view 
torch.from_numpy(data) # factory function

tensor([1, 2, 3])

In [ ]:
torch.get_default_dtype()

torch.float32

# Creating data from tensors directly

In [ ]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [ ]:
torch.zeros(2,2) 

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,2)

tensor([[0.2528, 0.6022],
        [0.5961, 0.0506]])

# Reshaping tensors

In [ ]:
t = torch.tensor([
    [1,2,3,4],
    [2,3,3,3],
    [1,0,0,0]
], dtype=torch.float32)

In [ ]:
t.shape,t.dtype,t.numel()

(torch.Size([3, 4]), torch.float32, 12)