# BroadCasting

In [1]:
import numpy as np

In [72]:
np.array([1,2,3]) + 0.5

array([1.5, 2.5, 3.5])

In [74]:
np.array([[1,2,3],[4,5,6]]) + np.array([-1,0,1])

array([[0, 2, 4],
       [3, 5, 7]])

In [75]:
np.array([[1,2,3],[4,5,6]]) + np.array([-1,0])

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### Broadcasting Rules

Move backwards from last dimension, check if they are compatible 
i.e., either they are equal or one of them is 1.


In [76]:
foo = np.array([[1,2,3],[4,5,6]]) 

In [83]:
boo = np.array([-2,2])

In [84]:
foo.shape, boo.shape

((2, 3), (2,))

In [85]:
boo = boo.reshape(2,1)

In [86]:
boo.shape

(2, 1)

In [87]:
boo

array([[-2],
       [ 2]])

In [88]:
foo + boo # numpy will just copy the numbers in the unequal dimension 

array([[-1,  0,  1],
       [ 6,  7,  8]])

# Reshaping

In [91]:
foo = np.random.rand(2,4)

In [92]:
foo

array([[0.96028685, 0.43952924, 0.15776012, 0.12841449],
       [0.47250879, 0.60664552, 0.97463936, 0.94992592]])

In [94]:
foo.reshape(4,2, order='C') # C style i.e., row major, i.e. first all the first axis elements are converted

array([[0.96028685, 0.43952924],
       [0.15776012, 0.12841449],
       [0.47250879, 0.60664552],
       [0.97463936, 0.94992592]])

In [95]:
foo.reshape(4,2, order='F') # Fortran style or column major order 

array([[0.96028685, 0.15776012],
       [0.47250879, 0.97463936],
       [0.43952924, 0.12841449],
       [0.60664552, 0.94992592]])

In [96]:
foo.reshape(2,2,2, order='C') 

array([[[0.96028685, 0.43952924],
        [0.15776012, 0.12841449]],

       [[0.47250879, 0.60664552],
        [0.97463936, 0.94992592]]])

In [97]:
foo.reshape(2,2,2, order='F') 

array([[[0.96028685, 0.15776012],
        [0.43952924, 0.12841449]],

       [[0.47250879, 0.97463936],
        [0.60664552, 0.94992592]]])

In [102]:
bar = np.array([[1,2,3,4],[5,6,7,8]])

In [103]:
bar.shape

(2, 4)

In [104]:
bar.reshape(2,2,2,order='F')

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [105]:
bar.shape =(2,2,2)

In [106]:
bar

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [107]:
bots = np.random.rand(2,3)

In [108]:
bots[[0,1],[1,0]] = np.nan

In [109]:
bots

array([[0.78289429,        nan, 0.54084695],
       [       nan, 0.33980781, 0.36465638]])

In [110]:
bots == np.nan

array([[False, False, False],
       [False, False, False]])

In [111]:
np.nan == np.nan

False

In [112]:
np.nan != np.nan

True

# Equivalence between NANs are not defined

In [113]:
np.isnan(bots) #only work for floats

array([[False,  True, False],
       [ True, False, False]])

In [115]:
np.array([np.inf,np.NINF])

array([ inf, -inf])

In [116]:
np.inf == np.inf, np.NINF == np.NINF

(True, True)

# Excercises

In [117]:
# 100 random scores to 10 people, find score[i] - score[j]

generator = np.random.default_rng(seed=42)

scores = np.round(generator.uniform(low=0,high=100,size=10),2)


In [118]:
scores

array([77.4 , 43.89, 85.86, 69.74,  9.42, 97.56, 76.11, 78.61, 12.81,
       45.04])

In [119]:
scores[:,None]

array([[77.4 ],
       [43.89],
       [85.86],
       [69.74],
       [ 9.42],
       [97.56],
       [76.11],
       [78.61],
       [12.81],
       [45.04]])

In [120]:
scores[None,:]

array([[77.4 , 43.89, 85.86, 69.74,  9.42, 97.56, 76.11, 78.61, 12.81,
        45.04]])

In [122]:
np.set_printoptions(linewidth=999)
np.abs(scores[:,None] - scores[None,:])

array([[ 0.  , 33.51,  8.46,  7.66, 67.98, 20.16,  1.29,  1.21, 64.59, 32.36],
       [33.51,  0.  , 41.97, 25.85, 34.47, 53.67, 32.22, 34.72, 31.08,  1.15],
       [ 8.46, 41.97,  0.  , 16.12, 76.44, 11.7 ,  9.75,  7.25, 73.05, 40.82],
       [ 7.66, 25.85, 16.12,  0.  , 60.32, 27.82,  6.37,  8.87, 56.93, 24.7 ],
       [67.98, 34.47, 76.44, 60.32,  0.  , 88.14, 66.69, 69.19,  3.39, 35.62],
       [20.16, 53.67, 11.7 , 27.82, 88.14,  0.  , 21.45, 18.95, 84.75, 52.52],
       [ 1.29, 32.22,  9.75,  6.37, 66.69, 21.45,  0.  ,  2.5 , 63.3 , 31.07],
       [ 1.21, 34.72,  7.25,  8.87, 69.19, 18.95,  2.5 ,  0.  , 65.8 , 33.57],
       [64.59, 31.08, 73.05, 56.93,  3.39, 84.75, 63.3 , 65.8 ,  0.  , 32.23],
       [32.36,  1.15, 40.82, 24.7 , 35.62, 52.52, 31.07, 33.57, 32.23,  0.  ]])

In [132]:
# Identify first three values < 60 and change them 0
scores = np.round(generator.integers(low=0,high=100,size=10),2)
scores

array([16, 75, 70, 35,  6, 97, 44, 89, 67, 77])

In [133]:
scores[np.argwhere(scores<60)[:3]]=0
scores

array([ 0, 75, 70,  0,  0, 97, 44, 89, 67, 77])