# Array Indexing

In [1]:
import numpy as np

In [2]:
foo = np.arange(3*2*4).reshape(3,2,4)

In [3]:
foo

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
foo[:,:,0]  # returns a 2D array

array([[ 0,  4],
       [ 8, 12],
       [16, 20]])

In [5]:
foo[:,:,[0,1]] # returns a 3d array

array([[[ 0,  1],
        [ 4,  5]],

       [[ 8,  9],
        [12, 13]],

       [[16, 17],
        [20, 21]]])

In [7]:
foo[ [[0,2],[2,0],[1,1]],
               [[0,0],[0,0],[1,1]],
                           [[0,1],[0,2],[0,3]]
   ]

array([[ 0, 17],
       [16,  2],
       [12, 15]])

In [8]:
foo = np.array([
    [10,20,30,40],
    [50,60,70,80]
])

In [9]:
foo[1,1] # assuming 8 byte int, we need to move to the second row i.e. 4x8 + 1x8 = 40 bytes to get to the element

60

In [10]:
foo.strides

(32, 8)

In [11]:
bar  = np.lib.stride_tricks.as_strided(
            x=foo,shape=(3,4),strides=(16,8)) # 16 bytes across rows and 8 bytes across columns

In [12]:
bar

array([[10, 20, 30, 40],
       [30, 40, 50, 60],
       [50, 60, 70, 80]])

In [13]:
bar[1,0]

30

# Einsum

In [14]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])

In [15]:
np.einsum('i,j->i',a,b) # https://www.youtube.com/watch?v=ULY6pncbRY8

array([ 0, 22, 44, 66])

In [16]:
np.einsum('i,j->',a,b) # for each i for each j output += Ai * Bj

132

In [17]:
labels = np.array([3,1,0,1])

In [20]:
one_hot_labels = np.lib.stride_tricks.as_strided(labels,shape=(4,4))

In [21]:
one_hot_labels

array([[                3,                 1,                 0,
                        1],
       [               48,               529,          31612848,
                 16076816],
       [                0,                 0,                 0,
                        0],
       [                0,                 0, 72340172838076672,
        72340172838076673]])